"""
CAM (Credit Appraisal Memo) template and prompt builder.
Produces structured prompts for the LLM based on the Five Cs of Credit.
The LLM is given ONLY structured data — it explains, not decides.
All scores, limits, and decisions come from the rules/ML engine.
"""

from typing import Dict, Any

CAM_SYSTEM_PROMPT = """
You are a senior credit analyst at a leading Indian bank (SBI/HDFC/Axis level).
You are writing a Credit Appraisal Memo (CAM) for the credit committee.

CRITICAL RULES:
1. You did NOT make the credit decision. The scoring engine did.
2. Your job is to explain the decision clearly and professionally.
3. Reference SPECIFIC data points from the structured inputs provided.
4. Use Indian banking terminology: MPBF, DSCR, TOL/TNW, NWC, DPG, ROC, etc.
5. Be concise but thorough. This document will be reviewed by the credit committee.
6. Never fabricate figures. If data is missing, state "Not Available."
7. Flag all risks explicitly, even if the decision is APPROVE.
"""


def _compute_de(f: Dict) -> Any:
    """
    Compute Debt-to-Equity ratio for display.

    Args:
        f: Financials dict.

    Returns:
        D/E ratio rounded to 2 decimal places, or "N/A".
    """
    debt = f.get("total_debt_crore") or 0
    equity = f.get("net_worth_crore") or 1
    return round(debt / equity, 2) if equity > 0 else "N/A"


def build_cam_prompt(state: dict) -> str:
    """
    Build the full CAM generation prompt with all state data injected.

    Args:
        state: Complete pipeline state dict.

    Returns:
        Formatted prompt string for LLM.
    """
    f = state.get("extracted_financials", {})

    return f"""{CAM_SYSTEM_PROMPT}

=== STRUCTURED INPUTS (DO NOT DEVIATE FROM THESE NUMBERS) ===

COMPANY: {state.get('company_name')}
DECISION: {state.get('decision')}
FINAL RISK SCORE: {state.get('final_risk_score')}/100 ({state.get('risk_category')} RISK)
RECOMMENDED LOAN LIMIT: ₹{state.get('recommended_loan_limit_crore')} Crore
INTEREST PREMIUM: {state.get('interest_rate_premium_bps')} bps over MCLR

FINANCIALS:
- Revenue (3 years): {f.get('revenue_crore')} Crore
- EBITDA Margin: {f.get('ebitda_margin_pct')}%
- PAT: ₹{f.get('pat_crore')} Crore
- DSCR: {f.get('dscr')}x
- Current Ratio: {f.get('current_ratio')}x
- Debt/Equity: {_compute_de(f)}x
- Net Worth: ₹{f.get('net_worth_crore')} Crore
- Total Debt: ₹{f.get('total_debt_crore')} Crore
- Auditor Opinion: {f.get('auditor_opinion')}
- Promoter Holding: {f.get('promoter_holding_pct')}%

GST & BANK:
- GST-Bank Mismatch: {state.get('gst_bank_mismatch_pct')}%
- Circular Trading: {'DETECTED - HIGH RISK' if state.get('circular_trading_detected') else 'Not detected'}

RESEARCH:
- Active Litigations: {len([c for c in state.get('litigation_data', []) if c.get('status') == 'pending'])}
- News Summary: {str(state.get('news_summary', 'No adverse news'))[:300]}
- Promoter Status: {state.get('promoter_background')}
- RBI Flags: {', '.join(state.get('rbi_regulatory_flags', [])) or 'None'}

RULE VIOLATIONS TRIGGERED:
{chr(10).join(state.get('rule_violations', ['None']))}

RISK STRENGTHS:
{chr(10).join(state.get('risk_strengths', ['None']))}

QUALITATIVE NOTES (Credit Officer):
{state.get('qualitative_notes', 'None provided')}
Factory Capacity: {state.get('site_visit_capacity_pct', 'Not visited')}%
Management Assessment: {state.get('management_assessment', 'None')}

=== WRITE THE CREDIT APPRAISAL MEMO WITH THESE EXACT SECTIONS ===

1. EXECUTIVE SUMMARY (3-4 sentences, include decision and key rationale)

2. BORROWER PROFILE (company background, promoters, sector, CIN)

3. FIVE Cs ANALYSIS:
   a. CHARACTER (promoter integrity, track record, MCA/court findings)
   b. CAPACITY (cash flows, DSCR, repayment ability)
   c. CAPITAL (net worth, leverage, balance sheet strength)
   d. COLLATERAL (assets pledged, MCA charges, security coverage)
   e. CONDITIONS (sector outlook, macro factors, RBI regulations)

4. FINANCIAL ANALYSIS (tabular summary, trend analysis, ratio benchmarks)

5. GST & BANKING CONDUCT ANALYSIS

6. RISK ASSESSMENT & RED FLAGS (cite specific sources for each flag)

7. RECOMMENDATION
   - Decision: {state.get('decision')}
   - Loan Limit: ₹{state.get('recommended_loan_limit_crore')} Crore
   - Interest Rate: MCLR + {state.get('interest_rate_premium_bps')}bps
   - Covenants (if Conditional Approve): list specific conditions
   - Rejection Rationale (if Reject): cite exact rule violations triggered

8. DECLARATION
   This CAM was generated by the Intelli-Credit AI system. Final decision authority
   rests with the authorized credit committee per RBI guidelines.
"""
