"""
Node 7: CAM (Credit Appraisal Memo) Generator
Generates professional CAM using LLM, then exports as DOCX and PDF.
All LLM calls go through llm_call() — never direct Gemini/OpenAI.
"""

import logging
import os

from backend.agents.state import CreditAppraisalState
from backend.agents.llm.llm_client import llm_call
from backend.cam.cam_template import build_cam_prompt
from backend.cam.docx_generator import generate_docx
from backend.cam.pdf_generator import generate_pdf

logger = logging.getLogger(__name__)


def cam_generator_node(state: CreditAppraisalState) -> CreditAppraisalState:
    """
    Generate Credit Appraisal Memo: LLM text + DOCX + PDF.

    Args:
        state: Current pipeline state with all scoring and research data.

    Returns:
        Updated state with CAM text and file paths.
    """
    state["log"].append("[CAM] Starting CAM generation...")

    # Build structured prompt
    prompt = build_cam_prompt(state)

    # Generate CAM text via LLM
    try:
        response = llm_call(prompt, task="cam_generation", max_tokens=4000)
        state["cam_text"] = response.text
        state["log"].append(
            f"[CAM] Text generated via {response.provider} ({response.latency_ms}ms)"
        )
    except Exception as e:
        logger.error(f"[CAM] LLM generation failed: {e}")
        state["cam_text"] = _generate_fallback_cam(state)
        state["errors"].append(f"[CAM] LLM failed, using template fallback: {e}")

    # Generate DOCX
    try:
        docx_path = generate_docx(state)
        state["cam_docx_path"] = docx_path
        state["log"].append(f"[CAM] DOCX generated: {docx_path}")
    except Exception as e:
        logger.error(f"[CAM] DOCX generation failed: {e}")
        state["errors"].append(f"[CAM] DOCX failed: {e}")

    # Generate PDF
    try:
        pdf_path = generate_pdf(state)
        state["cam_pdf_path"] = pdf_path
        state["log"].append(f"[CAM] PDF generated: {pdf_path}")
    except Exception as e:
        logger.error(f"[CAM] PDF generation failed: {e}")
        state["errors"].append(f"[CAM] PDF failed: {e}")

    state["current_node"] = "cam_generator"
    state["log"].append("[CAM] ✅ CAM generation complete")
    return state


def _generate_fallback_cam(state: dict) -> str:
    """
    Generate a basic CAM using template when LLM is unavailable.

    Args:
        state: Pipeline state.

    Returns:
        Basic CAM text string.
    """
    f = state.get("extracted_financials", {})
    return f"""
# CREDIT APPRAISAL MEMO — {state.get('company_name', 'Unknown')}

## EXECUTIVE SUMMARY
Decision: {state.get('decision', 'PENDING')}
Risk Score: {state.get('final_risk_score', 'N/A')}/100 ({state.get('risk_category', 'N/A')})
Recommended Limit: ₹{state.get('recommended_loan_limit_crore', 0)} Crore

## FINANCIAL HIGHLIGHTS
- Revenue: {f.get('revenue_crore', 'N/A')} Crore
- DSCR: {f.get('dscr', 'N/A')}x
- Current Ratio: {f.get('current_ratio', 'N/A')}x
- Net Worth: ₹{f.get('net_worth_crore', 'N/A')} Crore

## RISK FLAGS
{chr(10).join(state.get('rule_violations', ['None']))}

## STRENGTHS
{chr(10).join(state.get('risk_strengths', ['None']))}

---
Generated by Intelli-Credit AI | Decision authority: Credit Committee
"""
