"""
CAM section templates and helper labels.
"""

CAM_SECTION_ORDER = [
    "SECTION 1: EXECUTIVE SUMMARY",
    "SECTION 2: BORROWER PROFILE",
    "SECTION 3: THE FIVE Cs ANALYSIS",
    "SECTION 4: FINANCIAL ANALYSIS",
    "SECTION 5: RISK ASSESSMENT",
    "SECTION 6: RESEARCH FINDINGS",
    "SECTION 7: RECOMMENDATION",
    "SECTION 8: RISK MITIGANTS & CONDITIONS",
    "SECTION 9: ANNEXURES",
]

